<?php

namespace Carerix\Api\Rest\Entity;

/**
 * THIS FILE WAS GENERATED AUTOMATICALLY USING REST API ENTITY DESCRIBE SERVICE. DO NOT MODIFY IT.
 * YOUR CHANGES WILL BE LOST. INSTEAD MODIFY CONCRETE IMPLEMENTATION OF THIS CLASS IF NECESSARY.
 * @version Wed, 11 Oct 2023 09:45:58 +0000
 */
class CRMatchCriteria extends AbstractEntity\AbstractCRMatchCriteria
{
}
